name: CI/CD Pipeline # Name of the workflow
on: push:
branches:
- main # Trigger on pushes to 'main'
pull_request: branches:
- main # Trigger on pull requests to 'main'
jobs: build:
runs-on: ubuntu-latest # Use the latest Ubuntu runner
steps:
- name: Checkout Code
uses: actions/checkout@v2 # Fetch repository code
- name: Set up Node.js
uses: actions/setup-node@v2 with:
node-version: '14' # Specify Node.js version - name: Install Dependencies
run: npm install # Install project dependencies - name: Run Tests
run: npm test # Execute tests
deploy:
needs: build
runs-on: ubuntu-latest

steps:
- name: Checkout Code
uses: actions/checkout@v2
- name: Check if Azure App Service Exists id: check_app
run: |
if az webapp show --name "diverpracticewebapp2" --resource-group "nerodeanstorage1" >/dev/null 2>&1; then
echo "App Service Exists."
echo "exists=true" >> $GITHUB_ENV else
echo "App Service does not exist. Skipping deployment."
echo "exists=false" >> $GITHUB_ENV fi
continue-on-error: true
- name: Deploy to Azure App Service if: env.exists == 'true'
uses: azure/webapps-deploy@v2 with:
app-name:"diverpracticewebapp2"  
resource-group: "nerodeanstorage1"
publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} package: .
